package librarymanagement;



import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bsaik
 */
public class Home extends JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newStudentButton = new javax.swing.JButton();
        newBookButton = new javax.swing.JButton();
        statisticsButton = new javax.swing.JButton();
        issueBookButton = new javax.swing.JButton();
        returnBookButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        backgroundImageHomeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newStudentButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/images/member-add-on-300x300.png"))); // NOI18N
        newStudentButton.setText("New Student");
        newStudentButton.setPreferredSize(new java.awt.Dimension(159, 59));
        newStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 17, 170, -1));

        newBookButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/images/New book.png"))); // NOI18N
        newBookButton.setText("New Book");
        newBookButton.setPreferredSize(new java.awt.Dimension(159, 59));
        newBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 170, -1));

        statisticsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        statisticsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/images/Statics.png"))); // NOI18N
        statisticsButton.setText("Statistics");
        statisticsButton.setPreferredSize(new java.awt.Dimension(159, 59));
        statisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(statisticsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 170, -1));

        issueBookButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issueBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/images/issue.png"))); // NOI18N
        issueBookButton.setText("Issue Book");
        issueBookButton.setPreferredSize(new java.awt.Dimension(159, 59));
        issueBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookButtonActionPerformed(evt);
            }
        });
        getContentPane().add(issueBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 170, -1));

        returnBookButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/images/return-book-1-560407.png"))); // NOI18N
        returnBookButton.setText("Return Book");
        returnBookButton.setPreferredSize(new java.awt.Dimension(159, 59));
        returnBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 170, -1));

        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/images/exit.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setPreferredSize(new java.awt.Dimension(159, 59));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 170, -1));

        backgroundImageHomeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/images/Library_Book_532388_1366x768.jpg"))); // NOI18N
        getContentPane().add(backgroundImageHomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -2, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
//        setVisible(false);
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void newStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentButtonActionPerformed
        // TODO add your handling code here:
        new NewStudent().setVisible(true);
    }//GEN-LAST:event_newStudentButtonActionPerformed

    private void newBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookButtonActionPerformed
        // TODO add your handling code here:
        new NewBook().setVisible(true);
    }//GEN-LAST:event_newBookButtonActionPerformed

    private void issueBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookButtonActionPerformed
        // TODO add your handling code here:
        new IssueBook().setVisible(true);
    }//GEN-LAST:event_issueBookButtonActionPerformed

    private void returnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookButtonActionPerformed
        // TODO add your handling code here:
        new ReturnBook().setVisible(true);
    }//GEN-LAST:event_returnBookButtonActionPerformed

    private void statisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsButtonActionPerformed
        // TODO add your handling code here:
        new Statistics().setVisible(true);
    }//GEN-LAST:event_statisticsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImageHomeLabel;
    private javax.swing.JButton issueBookButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton newBookButton;
    private javax.swing.JButton newStudentButton;
    private javax.swing.JButton returnBookButton;
    private javax.swing.JButton statisticsButton;
    // End of variables declaration//GEN-END:variables
}
