package librarymanagement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.*;
import librarymanagement.Project.ConnectionProvider;
import javax.swing.JOptionPane;
/**
 *
 * @author bsaik
 */
public class NewBook extends javax.swing.JFrame {

    /**
     * Creates new form NewBook
     */
    public NewBook() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookIDLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        publisherLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        publishedYearLabel = new javax.swing.JLabel();
        bookIDTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        publisherTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        publishedYearTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookIDLabel.setText("Book ID");
        getContentPane().add(bookIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 104, -1, -1));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameLabel.setText("Name");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 148, -1, -1));

        publisherLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        publisherLabel.setText("Publisher");
        getContentPane().add(publisherLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 192, -1, -1));

        priceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        priceLabel.setText("Price");
        getContentPane().add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 236, -1, -1));

        publishedYearLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        publishedYearLabel.setText("Published Year");
        getContentPane().add(publishedYearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 280, -1, -1));

        bookIDTextField.setBackground(new java.awt.Color(255, 255, 204));
        bookIDTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIDTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(bookIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 101, 226, -1));

        nameTextField.setBackground(new java.awt.Color(255, 255, 204));
        nameTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 145, 226, -1));

        publisherTextField.setBackground(new java.awt.Color(255, 255, 204));
        publisherTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(publisherTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 189, 226, -1));

        priceTextField.setBackground(new java.awt.Color(255, 255, 204));
        priceTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(priceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 233, 226, -1));

        publishedYearTextField.setBackground(new java.awt.Color(255, 255, 204));
        publishedYearTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(publishedYearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 277, 226, -1));

        saveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-icon--1.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 321, -1, -1));

        closeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red-x-mark-transparent-background-3.png"))); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 321, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/123456.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIDTextFieldActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
//        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String bookID = bookIDTextField.getText();
        String name = nameTextField.getText();
        String publisher = publisherTextField.getText();
        String price = priceTextField.getText();
        String publishedYear = publishedYearTextField.getText();
        
        try
        {
            Connection con = ConnectionProvider.getCon();
            Statement statement = con.createStatement();
            statement.executeUpdate(String.format("insert into book values('%s','%s','%s','%s','%s')",
                                            bookID, name, publisher, price, publishedYear));
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            setVisible(false);
            new NewStudent().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "StudentID already exists");
            setVisible(false);
            new NewStudent().setVisible(true);
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookIDLabel;
    private javax.swing.JTextField bookIDTextField;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel publishedYearLabel;
    private javax.swing.JTextField publishedYearTextField;
    private javax.swing.JLabel publisherLabel;
    private javax.swing.JTextField publisherTextField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
